---
title: Student Growth Percentiles Calculations
subtitle: Re-evaluating Annual Census Testing
appendix-prefix: "B"
date: November 2022
author:
- name: Adam Van Iwaarden
  affiliation: "`r ifelse(grepl('working|draft', params$format), 'Center for Assessment', '')`"
- name: Leslie Keng
  affiliation: "`r ifelse(grepl('working|draft', params$format), 'Center for Assessment', '')`"
- name: Emma Klugman
  affiliation: Harvard University
bibliography: "`r cfaDocs:::cfa_shared_res('bib/cfa.bib')`"
link-citations: yes
toc: yes
toc-title: "`r ifelse(grepl('appendix', params$format), 'Appendix Contents', 'Report Contents')`"
paged-footnotes: yes
---

<!--
  This document was written by Adam R. Van Iwaarden for the Gates-Walton Foundations
    First Draft:  November 7, 2022
    Current Draft:  November 10, 2022
-->

```{r setup, echo = FALSE, include = FALSE}
  ###   Load R packages and functions required for HTML table creation silently.
  ###   Load SGP and other packages here to avoid messages.
  require(data.table)
  require(SGPdata)
  require(SGP)

  ###   set a global knitr options
  knitr::opts_chunk$set(
    cache.path = file.path("_cache", "SGP_Calc"),
    message = FALSE,
    warning = FALSE,
    prompt = FALSE  #  Avoid the "R>" and "R+" in code output for WP format
  )

  ###   Utility functions
  ord = \(x) { # <sup>th</sup>
    o <- toOrdinal::toOrdinal(as.numeric(x))
    return(paste0(x, "<sup>", substr(o, nchar(o)-1, nchar(o)), "</sup>"))
  }
```

```{asis, echo = grepl('working|draft', tolower(params$format))}
---
keywords: "draft -- do not cite"
abstract:
  This appendix contains example code used to conduct Phases 1 and 2 of the
  **\"Re-evaluating the Efficiency and Efficacy of Annual Census Standardized
  Testing for Accountability Purposes\"** study. In Phase 1 we prepare and
  format the data in a manner that will be consistent across all states and
  satisfies the requirements for growth analyses using the `SGP` software
  package. With the properly formatted data, we then proceed with the Student
  Growth Percentiles (SGP) analyses and school level results aggregations in
  the Phase 2 code.
---
```

```{r, echo = FALSE, results = "asis", eval = grepl("final", tolower(params$format))}
  inside.cover <- knitr::knit_child(input = cfaDocs:::cfa_paged_res("cfa/rmd/abstract_extra_yaml.Rmd"), quiet = TRUE)
  # no block text (`abstract: |-`)
  # single quote text (inside.cover), and use double-single quotes ('') in abstract_extra_yaml.Rmd

cat(paste0("
---
abstract: '", sub("\n\n  ", "", inside.cover), "'
---
"))
```

```{asis, echo = grepl("final", tolower(params$format))}
# Introduction

This report contains example code used to conduct Phases 1 and 2 of the
**\"Re-evaluating the Efficiency and Efficacy of Annual Census Standardized
Testing for Accountability Purposes\"** study. In Phase 1 we prepare and
format the student data in a manner that will be consistent across all states
and satisfies the requirements for growth analyses using the `SGP` software
package. With the properly formatted data, we then proceed with the Student
Growth Percentiles (SGP) analyses and school level results aggregations in
the Phase 2 code.

Each phase of this example analysis uses simulated state assessment data that is
available in the [`SGP` package](https://github.com/CenterForAssessment/SGP) [@sgp]
for the [`R` Software Environment](http://www.r-project.org/) [@Rsoftware].
This data is used here so that the interested reader can also run the code as
presented to reproduce the analytic workflow we have used for Phases 1 and 2 of
this report.

The dataset that is produced in the Phase 1 process represents an exemplar of
the data required for subsequent steps in this study. In this phase, each state
requires customized code adapted to the data as provided by each state's
education agency/authority. However, the end product in each state conforms to
the naming and data formatting conventions described and encoded here.

Given the properly cleaned and formatted data from Phase 1, each state's student
growth analyses follow a nearly identical workflow through each replicated
assessment condition. Each state's results are then aggregated at the school
level, again using an identical workflow.
```


```{r data-prep-r, echo = FALSE}
  knitr::spin_child("../State_A/Phase_1-Data_Prep-State_A.R")
```

```{r sgp-analysis-0, echo = FALSE}
  knitr::spin_child("../State_A/Phase_2-Growth_Analysis-State_A.R")
```

```{r aggr-v1, echo = FALSE}
  knitr::spin_child("../State_A/Phase_2-Results_Aggregation-State_A.R")
```

<!--  References  -->

# References {-}
::: {#refs}
:::
